

[[news]]
anews=""" 📣 Join and let's fuel the conversation with informed insights! 
We are now accepting proposals for questions to be included in our next waves. If you have a question you'd like to propose or a topic you think TAPP should cover, please send your suggestions and ideas to info@privacyperceptions.org. Your input is valuable in shaping discussion about AI and digital privacy."""
date="2024-12-10"

[[news]]
anews="""🚨 TAPP Wave 1 Data available at GESIS 🚨

The Transatlantic Privacy Perceptions (TAPP), Wave 1 (Fall 2022) data is now available at GESIS.

This study provides insights into the privacy perceptions of experts across multiple sectors and countries, including the US, UK, Germany, China, and others.
It explores the current and future challenges in digital privacy, focusing on laws, regulations, and corporate practices.

📊 Key Details:

Survey period: 09/13/2022 - 11/13/2022
Countries involved: AT, BE, CN, DE, NL, NO, GB, US
DOI: 10.4232/1.14198

Access the data and more at GESIS here: [https://search.gesis.org/research_data/ZA8757](https://search.gesis.org/research_data/ZA8757)"""
date="2024-11-25"
pin="true"

[[news]]
anews="""⏰Let's talk about Privacy 101 Part 2.

Earlier, I discussed what control over your own data means for users and companies, why it is important for AI, and how you can have more control over the data you share with AI algorithms. You can find the post here: https://lnkd.in/deu48y_6

Today, let's focus on privacy by design. According to our study, Transatlantic Privacy Perceptions (TAPP), 48% of our experts believe that privacy by design should be one of the guiding principles for developing AI frameworks and guidelines.

🤔What does privacy by design actually mean? It refers to integrating privacy into the design process from the very beginning, such as setting the highest privacy options as the default.

 ✍ Why is privacy by design important for AI? We share a lot of information either directly with chatbots or through the data that companies have about our behavior, preferences, purchases, and so on, which is then used to train AI models and develop more advanced chatbots. 

☑ For users, privacy by design reduces the mental load when using apps.
☑ Privacy by design significantly reduces the amount of user input data that a company can use for training AI or selling to another company to train their AI.
☑ It potentially reduces data leaks (if nothing is collected in the first place)
☑ While many companies discuss corporate digital responsibility 📣 , privacy by design would be an important and impactful practice in this area. 

🚀 What does privacy by design look like? For example, if ChatGPT had a "temporary chat" option set as the default and users had to opt in to share their chat history for future training, that would be an example of privacy by design.

If you want to learn more about the work we do at the Transatlantic Privacy Survey project, please visit: https://lnkd.in/dVctmQRp"""

date="2021-70-03"
originalurl="https://www.linkedin.com/posts/tapp-insights_activity-7221104622008995840-4O9c"
by="Olga Kononykhina"
pin="true"

[[news]]
anews="""⏰Data collection for the Transatlantic Privacy Perceptions survey is halfway through. 
As a privacy expert, your insights into the #AI tools and frameworks your organization/company is currently using, as well as the #governance and #privacy structures in place, are invaluable. Your participation will provide essential data that helps shape the dialogue on AI governance and privacy on both sides of the Atlantic. 

Please, do not delay your participation. Your contribution is vital, and together, we will make a significant impact.

⏱The survey will only take 2-5 minutes of your time. 

Join here: [https://lnkd.in/drDkthgp](https://lnkd.in/drDkthgp)

🎓TAPP is a research project conducted at the Universities of Maryland (UMD) 🇺🇸 and Munich (LMU) 🇩🇪.

📅The results will be published in June (we are all about speedy science 😎 ). You can find our previous results here. [https://lnkd.in/d3aN7i6w][https://lnkd.in/d3aN7i6w]"""
date="2021-70-03"
pin="true"
