name: Build and deploy to GitHub Pages

# Give GitHub Actions permission to push to your repo & Pages branch
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your source
      - uses: actions/checkout@v4
        with:
          persist-credentials: true   # make GITHUB_TOKEN available for pushes

      # 2) Install Zola
      - name: Install Zola
        uses: webfreak124/zola-action@v2
        with:
          version: "0.17.2"

      # 3) Build the site
      - name: Build with Zola
        run: zola build

      # 4) Deploy to gh-pages, skipping Jekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          skip_jekyll: true
