name: Build and deploy to GitHub pages

# allow the built-in token to push to your repo and Pages branch
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # ensure the token is available for pushes (this is the default)
        with:
          persist-credentials: true

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
