name: Build and deploy to GitHub pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: disable Jekyll on Pages
        run: |
          # make sure GitHub Pages won't try to run Jekyll
          touch public/.nojekyll

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
